---

## Gradle Install Tasks for Grouped Installs ##
- name: Create Gradle directory
  file:
    path: "{{ gradle_install_dir }}/gradle"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Unpack Gradle
  unarchive:
    src: "{{ gradle_download_destination }}/gradle-{{ gradle_version }}.zip"
    dest: "{{ gradle_install_dir }}/gradle"
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: Link Directory when Default
  file:
    src: "{{ gradle_install_dir }}/gradle/gradle-{{ gradle_version }}"
    dest: "{{ gradle_install_dir }}/gradle/default"
    state: link
    owner: root
    group: root
  when: gradle_default

- name: Link Directory when Latest
  file:
    src: "{{ gradle_install_dir }}/gradle/gradle-{{ gradle_version }}"
    dest: "{{ gradle_install_dir }}/gradle/latest"
    state: link
    owner: root
    group: root
  when: gradle_latest

- name: Link Gradle Binary when Default
  file:
    src: "{{ gradle_install_dir }}/gradle/gradle-{{ gradle_version }}/bin/gradle"
    dest: /usr/bin/gradle
    state: link
    owner: root
    group: root
  when: gradle_default